name: Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build API Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: false
        load: true
        tags: petfinder-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Public Profiles Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./public-profiles
        push: false
        load: true
        tags: petfinder-public-profiles:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Customer Portal Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./customer-portal
        push: false
        load: true
        tags: petfinder-customer-portal:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker Compose
      run: |
        docker-compose -f docker-compose.yml config
        echo "Docker Compose configuration is valid"